parameters:
     upload_directory: '%env(UPLOAD_DIRECTORY)%'

services:

    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ImageService:
            arguments:
                $uploadDirectory: '%kernel.project_dir%/public/uploads'
   
    App\Service\CommentFilterService: ~

    App\Controller\RegistrationController:
        tags: ['controller.service_arguments']
    App\Controller\LoginController:
        tags: ['controller.service_arguments']
    App\Controller\LogoutController:
        tags: ['controller.service_arguments']
    App\Service\AuthenticationService: ~
        
    App\Service\FakeMailer:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Component\Mailer\MailerInterface: '@App\Service\FakeMailer'
